# Generated by Django 4.0.5 on 2022-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\VScode_projects\\Django module\\Django_1st\\media', verbose_name='Картинка'),
        ),
    ]
