# Generated by Django 4.0.5 on 2022-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='C:\\VScode_projects\\Django module\\Django_1st\\media', verbose_name='Картинка')),
                ('number', models.IntegerField(blank=True, verbose_name='Номер картинки')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
