# Generated by Django 4.0.5 on 2022-06-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_description_long_place_description_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=1, max_length=100, verbose_name='ID места'),
            preserve_default=False,
        ),
    ]
