# Generated by Django 4.0.5 on 2022-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_image_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер картинки'),
        ),
    ]
