# Generated by Django 4.0.5 on 2022-06-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
